// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: game_statistic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerBoardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank int32  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PlayerBoardItem) Reset() {
	*x = PlayerBoardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_statistic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBoardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBoardItem) ProtoMessage() {}

func (x *PlayerBoardItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_statistic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBoardItem.ProtoReflect.Descriptor instead.
func (*PlayerBoardItem) Descriptor() ([]byte, []int) {
	return file_game_statistic_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerBoardItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerBoardItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GameStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid         string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PlayedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=playedAt,proto3" json:"playedAt,omitempty"`
	ScoreBilance int32                  `protobuf:"varint,3,opt,name=scoreBilance,proto3" json:"scoreBilance,omitempty"`
	PlayerBoard  []*PlayerBoardItem     `protobuf:"bytes,4,rep,name=playerBoard,proto3" json:"playerBoard,omitempty"`
	GameTitle    string                 `protobuf:"bytes,5,opt,name=gameTitle,proto3" json:"gameTitle,omitempty"`
}

func (x *GameStatistic) Reset() {
	*x = GameStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_statistic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatistic) ProtoMessage() {}

func (x *GameStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_game_statistic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatistic.ProtoReflect.Descriptor instead.
func (*GameStatistic) Descriptor() ([]byte, []int) {
	return file_game_statistic_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatistic) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GameStatistic) GetPlayedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PlayedAt
	}
	return nil
}

func (x *GameStatistic) GetScoreBilance() int32 {
	if x != nil {
		return x.ScoreBilance
	}
	return 0
}

func (x *GameStatistic) GetPlayerBoard() []*PlayerBoardItem {
	if x != nil {
		return x.PlayerBoard
	}
	return nil
}

func (x *GameStatistic) GetGameTitle() string {
	if x != nil {
		return x.GameTitle
	}
	return ""
}

var File_game_statistic_proto protoreflect.FileDescriptor

var file_game_statistic_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xdf, 0x01, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x69, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x69, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x75, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_statistic_proto_rawDescOnce sync.Once
	file_game_statistic_proto_rawDescData = file_game_statistic_proto_rawDesc
)

func file_game_statistic_proto_rawDescGZIP() []byte {
	file_game_statistic_proto_rawDescOnce.Do(func() {
		file_game_statistic_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_statistic_proto_rawDescData)
	})
	return file_game_statistic_proto_rawDescData
}

var file_game_statistic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_statistic_proto_goTypes = []interface{}{
	(*PlayerBoardItem)(nil),       // 0: gameStatistic.PlayerBoardItem
	(*GameStatistic)(nil),         // 1: gameStatistic.GameStatistic
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_game_statistic_proto_depIdxs = []int32{
	2, // 0: gameStatistic.GameStatistic.playedAt:type_name -> google.protobuf.Timestamp
	0, // 1: gameStatistic.GameStatistic.playerBoard:type_name -> gameStatistic.PlayerBoardItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_statistic_proto_init() }
func file_game_statistic_proto_init() {
	if File_game_statistic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_statistic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBoardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_statistic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_statistic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_statistic_proto_goTypes,
		DependencyIndexes: file_game_statistic_proto_depIdxs,
		MessageInfos:      file_game_statistic_proto_msgTypes,
	}.Build()
	File_game_statistic_proto = out.File
	file_game_statistic_proto_rawDesc = nil
	file_game_statistic_proto_goTypes = nil
	file_game_statistic_proto_depIdxs = nil
}
