// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"

	"github.com/google/uuid"
)

type Duouser struct {
	Uuid      uuid.UUID `json:"uuid"`
	Username  string    `json:"username"`
	PublicKey string    `json:"public_key"`
}

type Lobby struct {
	ID         int32     `json:"id"`
	OwnerID    uuid.UUID `json:"owner_id"`
	StackID    uuid.UUID `json:"stack_id"`
	MaxPlayers int32     `json:"max_players"`
}

type UserLogin struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	Challenge string    `json:"challenge"`
	LoginTime time.Time `json:"login_time"`
}
