// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Duouser, error)
	CreateUserLogin(ctx context.Context, arg CreateUserLoginParams) (UserLogin, error)
	DeleteUserLoginByUUID(ctx context.Context, userUuid uuid.UUID) (UserLogin, error)
	GetUserByUUID(ctx context.Context, uuid uuid.UUID) (Duouser, error)
	GetUserLoginByUUID(ctx context.Context, userUuid uuid.UUID) (UserLogin, error)
}

var _ Querier = (*Queries)(nil)
