// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (GameSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Duouser, error)
	CreateUserLogin(ctx context.Context, arg CreateUserLoginParams) (UserLogin, error)
	DeleteSessionByID(ctx context.Context, id int32) (GameSession, error)
	DeleteUserLoginByUUID(ctx context.Context, userUuid uuid.UUID) (UserLogin, error)
	GetSessionByID(ctx context.Context, id int32) (GameSession, error)
	GetSessionByOwnerUUID(ctx context.Context, ownerID uuid.UUID) (GameSession, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (Duouser, error)
	GetUserLoginByUUID(ctx context.Context, userUuid uuid.UUID) (UserLogin, error)
}

var _ Querier = (*Queries)(nil)
