// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO duouser (username, public_key) VALUES ($1, $2) RETURNING uuid, username, public_key
`

type CreateUserParams struct {
	Username  string `json:"username"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Duouser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PublicKey)
	var i Duouser
	err := row.Scan(&i.Uuid, &i.Username, &i.PublicKey)
	return i, err
}
